### ISSUE TITLE
Stitching ND2 files

### ISSUE THREAD

**Issue by tischi** [arjunrajlaboratory/DeepTile#2]
Hi, 

Thank you for creating this library.

We have one ND2 file that contains 9 positions, where each position contains 3 channels. Could your software stitch those 9 positions into one 3 channel image? 

The positions are sorted as 

```
1 2 3
6 5 4
7 8 9
```

Is that something that your software supports?

**Comment by zjniu** [comment]
Hi, thank you for your interest in this library, and my apologies for the delayed response! Yes, DeepTile supports stitching for such an ND2 file. Please see the notebook https://github.com/arjunrajlaboratory/DeepTile/blob/master/notebooks/nd2.ipynb for an example. If you need any help with it, please let me know.

**Comment by zjniu** [comment]
Closing this issue for now. Feel free to reopen if needed.
